---
- hosts: all
  vars:
    downloads_dir: /tmp/downloads
  tasks:
  - name: use whole partition
    become: true
    become_method: sudo
    command: resize2fs /dev/sda1

  - name: add apt repositories
    become: true
    become_method: sudo
    apt_repository: repo={{ item }}
    with_items:
    - ppa:git-core/ppa

  - name: install apt packages
    become: true
    become_method: sudo
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - automake
      - autotools-dev
      - build-essential
      - curl
      - debootstrap
      - direnv
      - exuberant-ctags
      - git
      - htop
      - libcap-dev
      - libncurses5-dev
      - libseccomp-dev
      - libtool
      - neovim
      - pkg-config
      - python-dev
      - python-pip
      - python3-dev
      - python3-pip
      - shellcheck
      - silversearcher-ag
      - tmux
      - tree
      - util-linux
      - valgrind
      - vim-nox
      - wget

  - name: install neovim pip package
    pip: name=neovim executable=/usr/bin/pip

  - name: install neovim pip3 package
    pip: name=neovim executable=/usr/bin/pip3

  - name: ensure downloads directory exists
    file: path={{downloads_dir}} state=directory

  - name: copy config files
    copy: src={{item.src}} dest={{item.dst}} mode=0664 force=true
    with_items:
    - {src: config/tmux.conf, dst: ~/.tmux.conf}
    - {src: config/gitconfig, dst: ~/.gitconfig}
    - {src: config/vimrc.local.plugins, dst: ~/.vimrc.local.plugins}

  - name: copy systemwide config files
    become: true
    become_method: sudo
    copy: src={{item.src}} dest={{item.dst}} mode=0664 force=true
    with_items:
    - {src: config/golang.sh, dst: /etc/profile.d/golang.sh}
    - {src: config/utils.sh, dst: /etc/profile.d/utils.sh}

  - name: get TPM
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: ~/.tmux/plugins/tpm

  - name: download go
    get_url: url=https://dl.google.com/go/go1.12.4.linux-amd64.tar.gz dest={{downloads_dir}}/go.tar.gz

  - name: extract go
    become: true
    become_method: sudo
    unarchive: copy=no src={{downloads_dir}}/go.tar.gz dest=/usr/local creates=/usr/local/go

  - name: clone vim config
    git: repo=https://github.com/luan/vimfiles dest=~/.vim

  - stat:
      path: /vagrant_data/src/github.com/opencontainers/runc
    register: runc_path

  - name: build runc
    make:
      chdir: /vagrant_data/src/github.com/opencontainers/runc
    environment:
      PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
      GOPATH: "/vagrant_data"
    when: runc_path.stat.isdir is defined and runc_path.stat.isdir

  - name: install runc
    make:
      chdir: /vagrant_data/src/github.com/opencontainers/runc
      target: install
    become: true
    become_method: sudo
    when: runc_path.stat.isdir is defined and runc_path.stat.isdir
